#LDFLAGS_STATIC=-static

CXXFLAGS= \
	-O2 \
	-g \
	$(shell curl-config --cflags) \
	$(shell xml2-config --cflags) \
	-Wall
LDFLAGS= $(LDFLAGS_STATIC) \
	-L/usr/X11R6/lib/ \
	-L/usr/users/troncon2/local/static/lib \
	$(shell curl-config --libs) \
	$(shell xml2-config --libs) \
	-ldl \
	-lXpm \
	-lX11 \
	-lpthread
